# Generated by Django 4.0 on 2021-12-23 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=360)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('people_required', models.SmallIntegerField()),
                ('people_joined', models.SmallIntegerField()),
                ('place', models.CharField(max_length=360)),
                ('price', models.IntegerField(blank=True)),
                ('categories', models.ManyToManyField(to='app.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='app.user')),
            ],
        ),
    ]
