# Generated by Django 4.0 on 2021-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_popularcategory_options_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
